### ISSUE TITLE
Error while running char-rnn.py

### ISSUE THREAD

**Issue by thadpasce16** [ppwwyyxx/tensorpack#121]
I am getting this error:

```
  File "char-rnn.py", line 72, in _build_graph
    cell = tf.contrib.rnn.BasicLSTMCell(num_units=param.rnn_size)
AttributeError: 'module' object has no attribute 'BasicLSTMCell'
```

Any resolution?

**Comment by thadpasce16** [comment]
I changed the BasicLSTMCell to LSTMBlockCell and it no longer complains. But I dont know what to replace for the MultiRNNCell.
It seems the TF API has changed.

**Comment by thadpasce16** [comment]
Apologies for churn. I was able to make the code run by making these changes:

```
cell = tf.nn.rnn_cell.BasicLSTMCell(num_units=param.rnn_size)
cell = tf.nn.rnn_cell.MultiRNNCell([cell] * param.num_rnn_layer)
outputs, last_state = tf.nn.rnn(cell, input_list, initial, scope='rnnlm')
```

I am using TF version 0.12

After training the model, how do I generate text? I am using this command line 
`python char-rnn.py --gpu 0,1 --load train_log/char-rnn/model-XXXX sample `
and getting errors.

**Comment by thadpasce16** [comment]
Error that I get is 

```
Traceback (most recent call last):
  File "./char-rnn.py", line 191, in <module>
    sample(args.load, args.start, args.num)
  File "./char-rnn.py", line 149, in sample
    state = model.initial.eval({input_vars[0]: dummy_input})
AttributeError: 'tuple' object has no attribute 'eval'
```

**Comment by a-maci** [comment]
I also noticed errors when running examples that use RNN/LSTM apis.
For instance, for PTB-LSTM example I am getting 

  File "/home/user/TF/tpNew/tensorpack/examples/PennTreebank/reader.py", line 118, in ptb_producer
    [batch_size, (i + 1) * num_steps])
TypeError: strided_slice() takes at least 4 arguments (3 given)

I saw that the TF APIs related to RNNs/LSTMs changed recently. Are these errors related to these API changes?

**Comment by ppwwyyxx** [comment]
TF makes some changes to the API of RNN/LSTMs. My code should work with the latest (unstable) version, but not the 12.1 release.

**Comment by ppwwyyxx** [comment]
TF 1.0.0rc0 was released yesterday. 
I found one more incompatible change from 12.1 to 1.0, so I updated the code a bit, now the code works with version 1.0.

**Comment by a-maci** [comment]
I updated to TF 1.0. Still facing some difficulties with the PTB example.

Getting this error now 

```
/usr/local/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:2889: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
Traceback (most recent call last):
  File "./PTB-LSTM.py", line 158, in <module>
    SimpleFeedfreeTrainer(config).train()
  File "/home/userID/TF/tensorpack/tensorpack/train/base.py", line 65, in train
    self.main_loop()
  File "/home/userID/TF/tensorpack/tensorpack/train/base.py", line 188, in main_loop
    self.trigger_epoch()
  File "/home/userID/TF/tensorpack/tensorpack/train/base.py", line 87, in trigger_epoch
    self.config.callbacks.trigger_epoch()
  File "/home/userID/TF/tensorpack/tensorpack/callbacks/base.py", line 98, in trigger_epoch
    self._trigger_epoch()
  File "/home/userID/TF/tensorpack/tensorpack/callbacks/group.py", line 124, in _trigger_epoch
    cb.trigger_epoch()
  File "/home/userID/TF/tensorpack/tensorpack/callbacks/base.py", line 98, in trigger_epoch
    self._trigger_epoch()
  File "/home/userID/TF/tensorpack/tensorpack/callbacks/base.py", line 155, in _trigger_epoch
    self.trigger()
  File "/home/userID/TF/tensorpack/tensorpack/callbacks/base.py", line 147, in trigger
    self._trigger()
  File "/home/userID/TF/tensorpack/tensorpack/callbacks/inference_runner.py", line 245, in _trigger
    self._write_summary_after_inference()
  File "/home/userID/TF/tensorpack/tensorpack/callbacks/inference_runner.py", line 248, in _write_summary_after_inference
    summary_inferencer(self.trainer, self.infs)
  File "/home/userID/TF/tensorpack/tensorpack/callbacks/inference_runner.py", line 56, in summary_inferencer
    ret = inf.after_inference()
  File "/home/userID/TF/tensorpack/tensorpack/callbacks/inference.py", line 52, in after_inference
    return self._after_inference()
  File "/home/userID/TF/tensorpack/tensorpack/callbacks/inference.py", line 101, in _after_inference
    assert len(self.stats) == len(self.names)
TypeError: object of type 'numpy.float64' has no len()
```

**Comment by a-maci** [comment]
BTW, the char-rnn example works fine for me with TF update to 1.0

**Comment by ppwwyyxx** [comment]
The PTB example works fine here. 
Looking from the log, you might not have the correct validation data.

**Comment by a-maci** [comment]
Yes, that was mistake at my end. The dataset hadnt downloaded properly.
